### ISSUE TITLE
Resolve all audit report issues

### ISSUE THREAD

**Issue by netpoe** [aufacicenta/pulsemarkets-v2-contracts#29]
Read through this doc https://blockchainassetregistry.infura-ipfs.io/ipfs/bafybeihnxtyxzfuz4nebvuamytgq74ifc5uxk4cexbphphtgc6npzwk7bq/Vibranium-Audit-for-Pulse-Markets%20(1).pdf — and resolve all issues as described in each. 

- [ ] Submit a single PR with all the issues resolved

**NOTE: 
do it in this repo**: https://github.com/aufacicenta/pulsemarkets/tree/prompt-wars/contracts

**Comment by susguzman** [comment]
Working in progress https://github.com/aufacicenta/pulsemarkets/tree/issue-29

**Comment by netpoe** [comment]
Made a clone of this issue: https://github.com/orgs/aufacicenta/projects/2/views/1?pane=issue&itemId=33127192
Closing this one.
